"use client";
import {useState} from "react";
import {ArrowRight,Check,ChevronDown,ChevronRight,Clock3,Eye,Figma,Layers3,Menu,Play,Sparkles,Star,X,Zap} from "lucide-react";

const items=[["01","SaaS Dashboard","violet"],["02","Fintech Platform","blue"],["03","AI Workspace","pink"],["04","Analytics Suite","orange"],["05","Mobile Banking","green"],["06","Creator Studio","cyan"]];
const faqs=[["What exactly is included?","A complete premium frontend system with responsive sections, product previews, interactions, pricing, FAQ and simulated cart states."],["Can I customize the templates?","Yes. Typography, colors, imagery, copy and sections are intentionally easy to replace."],["Is this a real checkout?","No. This phase is a frontend prototype. Cart and checkout are simulated locally; there is no Stripe, backend, email or database."],["Does it work on mobile?","Yes. Navigation, grids, typography and controls adapt for tablet and mobile screens."],["Can I use my own Figma files?","Yes. The preview frames are placeholders for your licensed Figma exports, screenshots or videos."]];

function Preview({tone}:{tone:string}){return <div className={"preview "+tone}><div className="pvbar"><i/><i/><i/><b>✦</b></div><div className="pvbody"><aside><i/><i/><i/><i/></aside><div className="pvmain"><span className="pvtitle"/><div className="pvcards"><i/><i/><i/></div><div className="pvchart"><i/><i/><i/><i/><i/></div></div></div></div>}

export default function Home(){
 const [menu,setMenu]=useState(false),[faq,setFaq]=useState<number|null>(0),[cart,setCart]=useState(false);
 return <main className="site">
  <nav className="nav"><a className="brand" href="#"><b>G</b><span>GRID</span></a><div className={"links "+(menu?"open":"")}><a href="#templates">Templates</a><a href="#features">Features</a><a href="#workflow">How it works</a><a href="#faq">FAQ</a><button onClick={()=>setCart(true)}>Get the pack <ArrowRight size={15}/></button></div><button className="navbuy" onClick={()=>setCart(true)}>Get the pack <ArrowRight size={15}/></button><button className="menub" onClick={()=>setMenu(!menu)}>{menu?<X/>:<Menu/>}</button></nav>

  <section className="hero"><div className="orb a"/><div className="orb b"/><div className="eyebrow"><Sparkles size={13}/> THE ULTIMATE FIGMA PROTOTYPE PACK</div><h1>Build faster.<br/><em>Design better.</em></h1><p className="lead">A premium collection of production-ready interfaces for ambitious digital products. Stop starting from zero and turn your next idea into a polished experience.</p><div className="actions"><button className="primary" onClick={()=>setCart(true)}>Explore the pack <ArrowRight/></button><a className="secondary" href="#templates"><Play size={14} fill="currentColor"/> See what's inside</a></div><div className="proof"><div className="avatars"><i>AH</i><i>MK</i><i>JS</i><i>+</i></div><div><div className="stars">{[1,2,3,4,5].map(x=><Star key={x} size={12} fill="currentColor"/>)}</div><small>Loved by 2,000+ designers & teams</small></div></div>
   <div className="hero-product"><div className="float-card left"><Layers3/>56 templates</div><div className="float-card right"><Zap/>Ready to customize</div><div className="browser"><div className="browserbar"><span>● ● ●</span><label>grid.design / workspace</label><b>● LIVE</b></div><div className="screen"><aside><strong>G</strong><i/><i className="on"/><i/><i/><i/></aside><div className="dashboard"><header><div><small>MONDAY, SEPTEMBER 18</small><h3>Good morning, Alex.</h3></div><button>+ New project</button></header><div className="metrics">{["Revenue","Active users","Conversion"].map((x,i)=><div key={x}><small>{x}</small><b>{i===0?"$128,420":i===1?"24,892":"7.84%"}</b><em>↗ {i===0?"18.4":"8.2"}%</em></div>)}</div><div className="dashgrid"><div className="chart"><b>Performance</b><span>Last 30 days⌄</span><svg viewBox="0 0 600 180" preserveAspectRatio="none"><path d="M0 145 C65 138 80 115 130 125 S190 70 240 102 S310 30 360 70 S420 110 465 50 S540 90 600 15" fill="none" stroke="currentColor" strokeWidth="4"/></svg></div><div className="activity"><b>Recent activity</b>{["Project Atlas","New teammate","Invoice paid","Design review"].map((x,i)=><p key={x}><i/>{x}<small>{i+2}m</small></p>)}</div></div></div></div></div></div>
  </section>

  <div className="logos"><span>TRUSTED BY DESIGNERS AT</span><b>northstar</b><b>MONO</b><b>orbit</b><b>lattice</b><b>vertex</b></div>

  <section id="templates" className="section"><div className="sectionhead"><div><div className="eyebrow">THE COLLECTION</div><h2>Everything you need to<br/><em>ship the idea.</em></h2></div><p>From first click to final handoff, every screen is crafted to help you move from concept to credible product faster.</p></div><div className="grid">{items.map(([n,title,tone])=><article className="template" key={n}><div className="meta"><span>{n}</span><small>Figma-ready</small></div><Preview tone={tone}/><div className="templatefoot"><h3>{title}</h3><ChevronRight size={17}/></div></article>)}</div></section>

  <section id="features" className="feature"><div className="featurecopy"><div className="eyebrow">BUILT FOR MOMENTUM</div><h2>Less pixel pushing.<br/><em>More product thinking.</em></h2><p>Good design should make the next decision obvious. Start with a strong visual language and spend your time on the product itself.</p><div className="checks"><span><Check/>Thoughtful responsive layouts</span><span><Check/>Reusable component patterns</span><span><Check/>Real-world states & edge cases</span><span><Check/>Clean, handoff-ready structure</span></div><button className="textbtn" onClick={()=>setCart(true)}>Get instant access <ArrowRight size={15}/></button></div><div className="art"><div className="artwindow"><div className="toolbar">● ● ● <span>Project overview</span></div><div className="artbody"><aside><b>Overview</b><span>Projects</span><span>Analytics</span><span>Team</span><span>Settings</span></aside><div className="artcontent"><div className="arthead"/><div className="artstats"><i/><i/><i/></div><div className="artpanels"><i/><i/></div></div></div></div><div className="badge"><Figma size={16}/> Figma-ready</div></div></section>

  <section id="workflow" className="section workflow"><div className="center"><div className="eyebrow">YOUR NEW WORKFLOW</div><h2>From blank canvas to<br/><em>beautiful product.</em></h2></div><div className="steps">{[[Clock3,"Pick a starting point","Choose the flow that matches your product and make it yours."],[Eye,"Shape the experience","Swap content, tune the visual system and connect your screens."],[Zap,"Ship with confidence","Present a polished prototype that feels like the real thing."]].map(([Icon,title,copy],i)=><div key={title as string}><small>0{i+1}</small><Icon/><h3>{title as string}</h3><p>{copy as string}</p></div>)}</div></section>

  <section className="pricing"><div><div className="eyebrow">ONE-TIME ACCESS</div><h2>Your next great product<br/><em>starts here.</em></h2><p>Get the complete frontend prototype experience and customize it around your own brand.</p></div><div className="pricecard"><div className="pricetop"><span>THE COMPLETE PACK</span><b>56 screens</b></div><div className="price"><small>$</small>79</div><p>One-time payment · lifetime access</p><button className="primary wide" onClick={()=>setCart(true)}>Get the complete pack <ArrowRight size={17}/></button><small className="secure"><Check/> Instant access · No subscription</small></div></section>

  <section id="faq" className="section faq"><div><div className="eyebrow">QUESTIONS</div><h2>Good questions.<br/><em>Clear answers.</em></h2></div><div className="faqs">{faqs.map(([q,a],i)=><div className={"faq "+(faq===i?"active":"")} key={q}><button onClick={()=>setFaq(faq===i?null:i)}><span>{q}</span><ChevronDown/></button>{faq===i&&<p>{a}</p>}</div>)}</div></section>
  <footer><a className="brand" href="#"><b>G</b><span>GRID</span></a><span>Designed for people who build.</span><div><a href="#templates">Templates</a><a href="#faq">FAQ</a></div></footer>

  {cart&&<div className="backdrop" onMouseDown={()=>setCart(false)}><aside className="cart" onMouseDown={e=>e.stopPropagation()}><button className="close" onClick={()=>setCart(false)}><X/></button><div className="eyebrow">YOUR ACCESS</div><h2>Complete<br/><em>Prototype Pack</em></h2><div className="cartitem"><Preview tone="violet"/><div><b>56-screen collection</b><span>Figma-ready UI system</span><span>Lifetime access</span></div></div><div className="subtotal"><span>Subtotal</span><b>$79</b></div><button className="primary wide" onClick={()=>setCart(false)}>Continue to preview <ArrowRight size={17}/></button><p className="note">Prototype only — no payment is processed.</p></aside></div>}
 </main>
}
